name: Deploy goboscript project to GitHub Pages
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - uses: actions/checkout@v4
            - run: bun install
            - run: sudo apt-get update && sudo apt-get install -y curl grep coreutils
            - run: python -m pip install matplotlib numpy pillow
            - run: >-
                  curl -L $(
                  curl -s https://api.github.com/repos/aspizu/goboscript/releases/latest |
                  grep browser_download_url |
                  grep goboscript_Linux_x86_64.tar.gz |
                  cut -d '"' -f 4) -o goboscript.tar.gz;
                  tar -xvf goboscript.tar.gz;
                  chmod +x goboscript;
            - run: bun run build
            - uses: actions/upload-pages-artifact@v3
    # Deployment job
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
